In [1]:
# importamos las librerías que necesitamos

# Tratamiento de datos
# -----------------------------------------------------------------------
import pandas as pd
import numpy as np


# -----------------------------------------------------------------------
pd.set_option('display.max_columns', None) # para poder visualizar todas las columnas de los DataFrames

# Gestión de los warnings
# -----------------------------------------------------------------------
import warnings
warnings.filterwarnings("ignore")

In [4]:
# cargamos el dataframe correspondiente 
df = pd.read_csv("archivos/Top 20 Holiday Songs 2011 - 2018.csv", index_col=0)

display(df.head(25))

,Year,Position,Song,Artist,Chart Date
index,,,,,
0,2011,1,All I Want For Christmas Is You,Mariah Carey,12/10/2011
1,2011,2,Mistletoe,Justin Bieber,12/10/2011
2,2011,3,Rockin' Around The Christmas Tree,Brenda Lee,12/10/2011
3,2011,4,The Christmas Song (Merry Christmas To You),Nat King Cole,12/10/2011
4,2011,5,Jingle Bell Rock,Bobby Helms,12/10/2011
5,2011,6,A Holly Jolly Christmas,Burl Ives,12/10/2011
6,2011,7,Feliz Navidad,Jose Feliciano,12/10/2011
7,2011,8,It's The Most Wonderful Time Of The Year,Andy Williams,12/10/2011
8,2011,9,Happy Xmas (War Is Over),John Lennon & Yoko Ono,12/10/2011
9,2011,10,Last Christmas,Wham!,12/10/2011
10,2011,11,White Christmas,Bing Crosby,12/10/2011
11,2011,12,Christmas Canon,Trans-Siberian Orchestra,12/10/2011
12,2011,13,Christmas Eve (Sarajevo 12/24),Trans-Siberian Orchestra,12/10/2011
13,2011,14,Do They Know It's Christmas?,Band-Aid,12/10/2011
14,2011,15,Rudolph The Red-Nosed Reindeer,Gene Autry,12/10/2011
15,2011,16,Where Are You Christmas?,Faith Hill,12/10/2011
16,2011,17,Wonderful Christmastime,Paul McCartney,12/10/2011
17,2011,18,It's Beginning To Look A Lot Like Christmas,Bing Crosby,12/10/2011
18,2011,19,Please Come Home For Christmas,Eagles,12/10/2011
19,2011,20,Sleigh Ride,Leroy Anderson,12/10/2011
20,2012,1,All I Want For Christmas Is You,Mariah Carey,12/8/2012
21,2012,2,Rockin' Around The Christmas Tree,Brenda Lee,12/8/2012
22,2012,3,The Christmas Song (Merry Christmas To You),Nat King Cole,12/8/2012
23,2012,4,Jingle Bell Rock,Bobby Helms,12/8/2012
24,2012,5,A Holly Jolly Christmas,Burl Ives,12/8/2012

In [5]:
def exploracion(df):
    df_info = pd.DataFrame()
    df_info["% nulos"] = round(df.isna().sum()/df.shape[0]*100, 2).astype(str)+"%"
    df_info["% no_nulos"] = round(df.notna().sum()/df.shape[0]*100, 2).astype(str)+"%"
    df_info["tipo_dato"] = df.dtypes
    df_info["num_valores_unicos"] = df.nunique()
    print(f"""El DataFrame tiene {df.shape[0]} filas y {df.shape[1]} columnas.
Tiene {df.duplicated().sum()} datos duplicados, lo que supone un porcentaje de {round(df.duplicated().sum()/df.shape[0], 2)}% de los datos.
Hay {len(list(df_info[(df_info["% nulos"] != "0.0%")].index))} columnas con datos nulos, y son:
{list(df_info[(df_info["% nulos"] != "0.0%")].index)}
y sin nulos hay {len(list(df_info[(df_info["% nulos"] == "0.0%")].index))} columnas y son:
{list(df_info[(df_info["% nulos"] == "0.0%")].index)}
A continuación tienes un detalle sobre los datos nulos y los tipos y número de datos:""")
    display(df_info.head())
    print("Principales estadísticos de las columnas categóricas:")
    display(df.describe(include="O").T)
    print("Principales estadísticos de las columnas numéricas:")
    display(df.describe(exclude="O").T)
    return df_info

exploracion(df)

El DataFrame tiene 160 filas y 5 columnas.
Tiene 0 datos duplicados, lo que supone un porcentaje de 0.0% de los datos.
Hay 0 columnas con datos nulos, y son:
[]
y sin nulos hay 5 columnas y son:
['Year', 'Position', 'Song', 'Artist', 'Chart Date']
A continuación tienes un detalle sobre los datos nulos y los tipos y número de datos:

           % nulos % no_nulos tipo_dato  num_valores_unicos
Year          0.0%     100.0%     int64                   8
Position      0.0%     100.0%     int64                  20
Song          0.0%     100.0%    object                  31
Artist        0.0%     100.0%    object                  29
Chart Date    0.0%     100.0%    object                   8

Principales estadísticos de las columnas categóricas:

           count unique                                          top freq
Song         160     31  It's Beginning To Look A Lot Like Christmas   14
Artist       160     29                     Trans-Siberian Orchestra   12
Chart Date   160      8                                   12/10/2011   20

Principales estadísticos de las columnas numéricas:

          count    mean       std     min      25%     50%      75%     max
Year      160.0  2014.5  2.298482  2011.0  2012.75  2014.5  2016.25  2018.0
Position  160.0    10.5  5.784386     1.0     5.75    10.5    15.25    20.0

           % nulos % no_nulos tipo_dato  num_valores_unicos
Year          0.0%     100.0%     int64                   8
Position      0.0%     100.0%     int64                  20
Song          0.0%     100.0%    object                  31
Artist        0.0%     100.0%    object                  29
Chart Date    0.0%     100.0%    object                   8